spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:22936/local
    username: ${DATASOURCE_ID}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    kr.ac.kumoh.polaris: debug

springdoc:
  trim-kotlin-indent: true
  packagesToScan: kr.ac.kumoh.polaris
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    enabled: false
    operations-sorter: alpha
    display-request-duration: true
    tags-sorter: alpha
  api-docs:
    enabled: true
    groups:
      enabled: false

core:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "https://localhost:3000"
