spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/local
    username: ${DATASOURCE_ID}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: validate

logging:
  level:
    kr.ac.kumoh.polaris: debug

## 이 설정을 변경하지 마십시오. OpenAPI는 로컬 환경에서만 사용하세요.
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

core:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "https://localhost:3000"
