spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:22936/local
    username: ${DATASOURCE_ID}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    kr.ac.kumoh.polaris: debug

springdoc:
  trim-kotlin-indent: true
  packagesToScan: kr.ac.kumoh.polaris
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    enabled: false
    operations-sorter: alpha
    display-request-duration: true
    tags-sorter: alpha
  api-docs:
    enabled: true
    groups:
      enabled: false

core:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "https://localhost:3000"
    allowed-methods: [ "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS" ]
    allowed-headers: [ "*" ]
    exposed-headers: [ ]
    allow-credentials: true
    max-age: 3600
  openapi:
    data4library:
      base-url: "http://data4library.kr"
      auth-key: ${DATA4LIBRARY_AUTH_KEY}
    naver:
      search:
        list:
          base-url: "https://openapi.naver.com//v1/search/book.json"
          client-id: ${NAVER_BOOK_SEARCH_LIST_CLIENT_ID}
          client-secret: ${NAVER_BOOK_SEARCH_LIST_CLIENT_SECRET}
        detail:
          base-url: "https://openapi.naver.com/v1/search/book_adv.json"
          client-id: ${NAVER_BOOK_SEARCH_DETAIL_CLIENT_ID}
          client-secret: ${NAVER_BOOK_SEARCH_DETAIL_CLIENT_SECRET}
