spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: 'jdbc:mariadb://localhost:22936/local?serverTimezone=Asia/Seoul'
    username: ${DATASOURCE_ID}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
    show-sql: true

core:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "https://localhost:3000"
    allowed-methods: [ "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS" ]
    allowed-headers: [ "*" ]
    exposed-headers: [ ]
    allow-credentials: true
    max-age: 3600
