spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/local
    username: ${DATASOURCE_ID}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: validate

logging:
  level:
    kr.ac.kumoh.polaris: debug

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

core:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "https://localhost:3000"
    allowed-methods: [ "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS" ]
    allowed-headers: [ "*" ]
    exposed-headers: [ ]
    allow-credentials: true
    max-age: 3600
  openapi:
    data4library:
      base-url: "http://data4library.kr"
      auth-key: ${DATA4LIBRARY_AUTH_KEY}
    naver:
      search:
        list:
          base-url: "https://openapi.naver.com//v1/search/book.json"
          client-id: ${NAVER_BOOK_SEARCH_LIST_CLIENT_ID}
          client-secret: ${NAVER_BOOK_SEARCH_LIST_CLIENT_SECRET}
        detail:
          base-url: "https://openapi.naver.com/v1/search/book_adv.json"
          client-id: ${NAVER_BOOK_SEARCH_DETAIL_CLIENT_ID}
          client-secret: ${NAVER_BOOK_SEARCH_DETAIL_CLIENT_SECRET}
